# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_aa_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formAaGraphics(object):
    def setupUi(self, formAaGraphics):
        formAaGraphics.setObjectName("formAaGraphics")
        formAaGraphics.resize(739, 756)
        self.widgetAaX = GraphicsLayoutWidget(formAaGraphics)
        self.widgetAaX.setGeometry(QtCore.QRect(0, 0, 741, 251))
        self.widgetAaX.setObjectName("widgetAaX")
        self.widgetAaY = GraphicsLayoutWidget(formAaGraphics)
        self.widgetAaY.setGeometry(QtCore.QRect(0, 250, 741, 251))
        self.widgetAaY.setObjectName("widgetAaY")
        self.widgetAaZ = GraphicsLayoutWidget(formAaGraphics)
        self.widgetAaZ.setGeometry(QtCore.QRect(0, 500, 741, 251))
        self.widgetAaZ.setObjectName("widgetAaZ")

        self.retranslateUi(formAaGraphics)
        QtCore.QMetaObject.connectSlotsByName(formAaGraphics)

    def retranslateUi(self, formAaGraphics):
        _translate = QtCore.QCoreApplication.translate
        formAaGraphics.setWindowTitle(_translate("formAaGraphics", "All Accle "))
from pyqtgraph import GraphicsLayoutWidget
