# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_raw_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formGraphics(object):
    def setupUi(self, formGraphics):
        formGraphics.setObjectName("formGraphics")
        formGraphics.resize(830, 530)
        self.graphWidget = GraphicsLayoutWidget(formGraphics)
        self.graphWidget.setGeometry(QtCore.QRect(0, 0, 831, 531))
        self.graphWidget.setObjectName("graphWidget")

        self.retranslateUi(formGraphics)
        QtCore.QMetaObject.connectSlotsByName(formGraphics)

    def retranslateUi(self, formGraphics):
        _translate = QtCore.QCoreApplication.translate
        formGraphics.setWindowTitle(_translate("formGraphics", "G-Sensor 動態圖"))
from pyqtgraph import GraphicsLayoutWidget
